Avoid crash when BOWER_COMPONENTS_ROOT's parent doesn't exist
If BOWER_COMPONENTS_ROOT points to a path consisting of more than one
non-existent subdirectory, BowerAdapter.create_components_root() will
crash with a message like:

OSError: [Errno 2] No such file or directory: '/path/to/directory'

This fix replaces the os.mkdir() call with os.makedirs(), which will
create all the missing intermediate directories as needed.